---
- hosts: all
  become: true
  tasks:

    - name: install packages
      apt:
        name: [
          'apt-transport-https',
          'bash-completion',
          'curl',
          'git',
          'htop',
          'mlocate',
          'python3-dev',
          'python3-minimal',
          'python3-pip',
          'screen',
          'vim',
        ]
        state: present
        update_cache: true

