apiVersion: v1
kind: Pod
metadata:
  name: secret-as-file-example
spec:
  containers:
    - name: client-container
      image: k8s.gcr.io/busybox
      command: ["sh", "-c"]
      args:
      - while true; do
          sleep 5;
        done;
      volumeMounts:
        - name: secret
          mountPath: /etc/secrets
          readOnly: true
        - name: docker-config
          mountPath: /kaniko/.docker
          readOnly: true
  volumes:
    - name: secret
      secret:
        secretName: example-secret
    - name: docker-config
      secret:
        secretName: docker-auth-config

